
import java.util.Random;
import javax.swing.JOptionPane;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC-PC-PC-PC
 */
public class AFD extends javax.swing.JFrame {

   int menang = 0;
   int kalah = 0;
   int draw = 0;
   int giliranmain = 0;
   
    /**
     * Creates new form AFD
     */
    public AFD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Start = new javax.swing.JRadioButton();
        tulis = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        inputnama = new javax.swing.JTextField();
        background1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Batu = new javax.swing.JRadioButton();
        tulis1 = new javax.swing.JLabel();
        Gunting = new javax.swing.JRadioButton();
        LabelNama2 = new javax.swing.JLabel();
        Namapemain = new javax.swing.JLabel();
        Kertas = new javax.swing.JRadioButton();
        Paper2 = new javax.swing.JRadioButton();
        LabelAnda = new javax.swing.JLabel();
        Rock2 = new javax.swing.JRadioButton();
        Scissor2 = new javax.swing.JRadioButton();
        LblPilBatu = new javax.swing.JLabel();
        LblPilGunting = new javax.swing.JLabel();
        LblPilkertas2 = new javax.swing.JLabel();
        LabelAnda1 = new javax.swing.JLabel();
        Rock3 = new javax.swing.JRadioButton();
        Paper3 = new javax.swing.JRadioButton();
        Scissors3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblMenang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblKalah = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblSeri = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setEnabled(false);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 450));
        jPanel1.setLayout(null);

        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Start.png"))); // NOI18N
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start);
        Start.setBounds(180, 280, 150, 90);

        tulis.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tulis.setForeground(new java.awt.Color(255, 255, 255));
        tulis.setText("Rock vs Scissor vs Paper");
        tulis.setToolTipText("");
        jPanel1.add(tulis);
        tulis.setBounds(130, 0, 260, 60);

        LabelNama.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama.setText("Masukan Nama Anda :");
        jPanel1.add(LabelNama);
        LabelNama.setBounds(160, 50, 180, 80);
        jPanel1.add(inputnama);
        inputnama.setBounds(160, 120, 180, 30);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        background1.setMaximumSize(new java.awt.Dimension(400, 300));
        background1.setMinimumSize(new java.awt.Dimension(400, 300));
        background1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.add(background1);
        background1.setBounds(0, -80, 500, 550);

        getContentPane().add(jPanel1, "card2");

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 450));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 450));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 450));
        jPanel2.setLayout(null);

        Batu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rock.png"))); // NOI18N
        Batu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatuMouseClicked(evt);
            }
        });
        jPanel2.add(Batu);
        Batu.setBounds(210, 170, 80, 90);

        tulis1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tulis1.setForeground(new java.awt.Color(255, 255, 255));
        tulis1.setText("Rock vs Scissor vs Paper");
        tulis1.setToolTipText("");
        jPanel2.add(tulis1);
        tulis1.setBounds(120, 0, 260, 60);

        Gunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scissors.png"))); // NOI18N
        Gunting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuntingMouseClicked(evt);
            }
        });
        jPanel2.add(Gunting);
        Gunting.setBounds(360, 170, 79, 90);

        LabelNama2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LabelNama2.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama2.setText("Nama Pemain :");
        jPanel2.add(LabelNama2);
        LabelNama2.setBounds(40, 60, 130, 60);

        Namapemain.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Namapemain.setForeground(new java.awt.Color(255, 255, 255));
        Namapemain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(Namapemain);
        Namapemain.setBounds(170, 80, 310, 20);

        Kertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paper.png"))); // NOI18N
        Kertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KertasMouseClicked(evt);
            }
        });
        jPanel2.add(Kertas);
        Kertas.setBounds(70, 170, 80, 90);

        Paper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paper.png"))); // NOI18N
        jPanel2.add(Paper2);
        Paper2.setBounds(70, 300, 79, 110);

        LabelAnda.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LabelAnda.setForeground(new java.awt.Color(255, 255, 255));
        LabelAnda.setText("Pilihan CPU :");
        jPanel2.add(LabelAnda);
        LabelAnda.setBounds(360, 270, 100, 25);

        Rock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rock.png"))); // NOI18N
        jPanel2.add(Rock2);
        Rock2.setBounds(70, 300, 80, 110);

        Scissor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scissors.png"))); // NOI18N
        jPanel2.add(Scissor2);
        Scissor2.setBounds(70, 300, 80, 110);

        LblPilBatu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblPilBatu.setForeground(new java.awt.Color(255, 255, 255));
        LblPilBatu.setText("Batu");
        jPanel2.add(LblPilBatu);
        LblPilBatu.setBounds(230, 140, 40, 20);

        LblPilGunting.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblPilGunting.setForeground(new java.awt.Color(255, 255, 255));
        LblPilGunting.setText("Gunting");
        jPanel2.add(LblPilGunting);
        LblPilGunting.setBounds(370, 130, 70, 30);

        LblPilkertas2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblPilkertas2.setForeground(new java.awt.Color(255, 255, 255));
        LblPilkertas2.setText("Kertas");
        jPanel2.add(LblPilkertas2);
        LblPilkertas2.setBounds(80, 140, 50, 20);

        LabelAnda1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LabelAnda1.setForeground(new java.awt.Color(255, 255, 255));
        LabelAnda1.setText("Pilihan Anda :");
        jPanel2.add(LabelAnda1);
        LabelAnda1.setBounds(70, 270, 120, 25);

        Rock3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rock.png"))); // NOI18N
        jPanel2.add(Rock3);
        Rock3.setBounds(370, 300, 80, 110);

        Paper3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paper.png"))); // NOI18N
        jPanel2.add(Paper3);
        Paper3.setBounds(370, 300, 79, 110);

        Scissors3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scissors.png"))); // NOI18N
        jPanel2.add(Scissors3);
        Scissors3.setBounds(370, 300, 79, 110);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Score anda :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(210, 290, 100, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menang :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 310, 90, 70);

        LblMenang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblMenang.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(LblMenang);
        LblMenang.setBounds(270, 340, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kalah :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 354, 40, 30);

        LblKalah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblKalah.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(LblKalah);
        LblKalah.setBounds(270, 360, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seri :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 380, 60, 20);

        LblSeri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblSeri.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(LblSeri);
        LblSeri.setBounds(270, 380, 60, 20);

        background2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        background2.setText("Kertas");
        background2.setToolTipText("");
        background2.setMaximumSize(new java.awt.Dimension(400, 350));
        background2.setMinimumSize(new java.awt.Dimension(400, 350));
        background2.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel2.add(background2);
        background2.setBounds(0, -80, 500, 550);

        getContentPane().add(jPanel2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        Namapemain.setText(inputnama.getText());
        Paper2.setVisible(false);
        Rock2.setVisible(false);
        Scissor2.setVisible(false);
        Paper3.setVisible(false);
        Rock3.setVisible(false);
        Scissors3.setVisible(false);
        
        
        
    }//GEN-LAST:event_StartActionPerformed

    private void KertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KertasMouseClicked
        // TODO add your handling code here:
        Paper2.setVisible(true);
        Rock2.setVisible(false);
        Scissor2.setVisible(false);
        Random random=new Random();
        int kom=random.nextInt(3);
        rule("KERTAS", kom);
        giliranmain = giliranmain+1;
    }//GEN-LAST:event_KertasMouseClicked

    private void BatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatuMouseClicked
        // TODO add your handling code here:
        Rock2.setVisible(true);
        Paper2.setVisible(false);
        Scissor2.setVisible(false);
        Random random=new Random();
        int kom=random.nextInt(3);
        rule("BATU", kom);
        giliranmain = giliranmain+1;
    }//GEN-LAST:event_BatuMouseClicked

    private void GuntingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuntingMouseClicked
        // TODO add your handling code here:
        Scissor2.setVisible(true);
        Rock2.setVisible(false);
        Paper2.setVisible(false);
        Random random=new Random();
        int kom=random.nextInt(3);
        rule("GUNTING", kom);
        giliranmain = giliranmain+1;
    }//GEN-LAST:event_GuntingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Batu;
    private javax.swing.JRadioButton Gunting;
    public javax.swing.JRadioButton Kertas;
    public javax.swing.JLabel LabelAnda;
    public javax.swing.JLabel LabelAnda1;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNama2;
    public javax.swing.JLabel LblKalah;
    public javax.swing.JLabel LblMenang;
    private javax.swing.JLabel LblPilBatu;
    private javax.swing.JLabel LblPilGunting;
    private javax.swing.JLabel LblPilkertas2;
    public javax.swing.JLabel LblSeri;
    public javax.swing.JLabel Namapemain;
    public javax.swing.JRadioButton Paper2;
    public javax.swing.JRadioButton Paper3;
    public javax.swing.JRadioButton Rock2;
    public javax.swing.JRadioButton Rock3;
    public javax.swing.JRadioButton Scissor2;
    public javax.swing.JRadioButton Scissors3;
    public javax.swing.JRadioButton Start;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    public javax.swing.JTextField inputnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel tulis;
    public javax.swing.JLabel tulis1;
    // End of variables declaration//GEN-END:variables


public void rule(String input, int kom){
    String pilihancpu;
        if(kom==1){
            pilihancpu="GUNTING";
            Scissors3.setVisible(true);
            Rock3.setVisible(false);
            Paper3.setVisible(false);
            
        }else{
            if(kom==2){
                pilihancpu="BATU";
                Rock3.setVisible(true);
                Scissors3.setVisible(false);
                Paper3.setVisible(false);
            }else{
                pilihancpu="KERTAS";
                Paper3.setVisible(true);
                Rock3.setVisible(false);
                Scissors3.setVisible(false);
 
            }
        }

if (input.equals(pilihancpu))
            {
                JOptionPane.showMessageDialog(null,"Kamu beruntung...Hasilnya imbang!");
                draw++;
                result();
                if(giliranmain > 8){
                JOptionPane.showMessageDialog(null,"Skor Anda : "
                +"\nMenang sebanyak "+menang
                +"\nKalah sebanyak "+kalah
                +"\nSeri sebanyak : "+draw);
                jPanel2.setVisible(false);
                jPanel1.setVisible(true);
                }
            }
            else if (input.equals("BATU"))
            {
                if (pilihancpu.equals("GUNTING")){
                    JOptionPane.showMessageDialog(null,"Batu menghancurkan Gunting. Kamu menang!!");
                    menang++;
                    result();
                                                }
                else{
                    if (pilihancpu.equals("KERTAS")){
                    JOptionPane.showMessageDialog(null,"Kertas membungkus Batu. Kamu kalah!!");
                    kalah++;
                    result();
                    
                                                    }
                    }
                if(giliranmain > 8){
                JOptionPane.showMessageDialog(null,"Skor Anda : "
                +"\nMenang sebanyak "+menang
                +"\nKalah sebanyak "+kalah
                +"\nSeri sebanyak : "+draw);
                jPanel2.setVisible(false);
                jPanel1.setVisible(true);
                }

            }
            else if (input.equals("KERTAS"))
            {
                if (pilihancpu.equals("GUNTING")){
                    JOptionPane.showMessageDialog(null,"Gunting memotong Kertas. Kamu kalah!!");
                    kalah++;
                    result();
                                                }
                else{
                    if (pilihancpu.equals("BATU")){
                    JOptionPane.showMessageDialog(null,"Kertas membungkus Batu. Kamu menang!!");
                    menang++;
                    result();  
                                                   }
                     }
                if(giliranmain > 8){
                JOptionPane.showMessageDialog(null,"Skor Anda : "
                +"\nMenang sebanyak "+menang
                +"\nKalah sebanyak "+kalah
                +"\nSeri sebanyak : "+draw);
                jPanel2.setVisible(false);
                jPanel1.setVisible(true);
                }
            }
            else if (input.equals("GUNTING"))
            {
                if (pilihancpu.equals("KERTAS")){
                    JOptionPane.showMessageDialog(null,"Gunting memotong Kertas. Kamu menang!!");
                    menang++;
                    result();
                                                }
                else{
                    if (pilihancpu.equals("BATU")){
                    JOptionPane.showMessageDialog(null,"Batu menghancurkan Gunting. Kamu kalah!!");
                    kalah++;
                    result();
                                                  }                    
                    }
                if(giliranmain > 8){
                JOptionPane.showMessageDialog(null,"Skor anda : "
                +"\nMenang sebanyak "+menang
                +"\nKalah sebanyak "+kalah
                +"\nSeri sebanyak : "+draw);
                jPanel2.setVisible(false);
                jPanel1.setVisible(true);
                }
            }
        }

 public void result(){
     String win= String.valueOf(menang);
     String lose = String.valueOf(kalah);
     String seri = String.valueOf(draw);
     LblMenang.setText(win);
     LblKalah.setText(lose);
     LblSeri.setText(seri);
        
 }
 
}

 
 







